### ISSUE TITLE
Implement a verbose option

### ISSUE THREAD

**Issue by RLesur** [RLesur/crrri#10]
In the current version, a lot of messages are written to the log. It could be annoying for higher level development. We have to implement a verbose option.

**Comment by cderv** [comment]
Are the message only for debug purposes for the developers ?

If so, I could be interesting to use [debugme](https://github.com/r-lib/debugme). It is very powerful and easy to use. As we are on a low level api, could be enough.

Otherwise, I think a global option `getOption("crrri.verbose")` could be a good idea to enable / disable at a session level. I think this is better than a verbose argument in functions.  If we want a user to have messages, we can also work on the returned value in console with `cli` like recent tidyverse tool. 

We can also do both, according the message nature (toward developers or users).

What do you think ?

**Comment by RLesur** [comment]
I didn't know `debugme`. This is awesome! 
There are two kinds of messages here: messages sent during connexion/deconnexion (mainly for crrri debugging) and messages tracking the exchanges between the R websocket client and the remote websocket server.
These lasts are essential for R devs when they will develop higher levels packages: during the development process and for debugging their packages.
I think that `debugme` could cover the entire needs.

**Comment by cderv** [comment]
Ok I'll go with debugme then. :)

**Comment by cderv** [comment]
Just a wild thought: Do you already have a script to test error message ? When it fails or succeed ?

**Comment by cderv** [comment]
There the chrome command launch that is remaining for `echo_cmd=TRUE` in `processx::process$new(`. 

Should we make this optional or always print the command ? Do you think it is this still required even for development ?

**Comment by RLesur** [comment]
> Just a wild thought: Do you already have a script to test error message ? When it fails or succeed ?

No, I haven't.

> There is the chrome command that is remaining as message because of `echo_cmd=TRUE` in `processx::process$new`.
> 
> Should we make this optional or always print the command ? Do you think it is this still required even for development ?

I found it useful when I developed the connexion functions (in order to compare behaviours depending on  proxy, os...). I don't know whether anyone needs this.
